const palette = {
  igBlue: '#0095F6',
  igBlueDark: '#1A8CD8',
  igBlueSoft: '#E8F5FE',
  igBlueSoftDark: '#0A2540',
  white: '#FFFFFF',
  offWhite: '#FAFAFA',
  nearBlack: '#262626',
  trueBlack: '#000000',
  surfaceDark: '#121212',
  cardDark: '#1C1C1C',
  mist: '#8E8E8E',
  mistLight: '#C7C7C7',
  hairline: '#DBDBDB',
  hairlineDark: '#262626',
  danger: '#ED4956',
  storyPink: '#F58529',
  storyOrange: '#DD2A7B',
  storyPurple: '#8134AF',
  accentGold: '#F5A623',
};

export default {
  light: {
    text: palette.nearBlack,
    textSecondary: '#8E8E8E',
    background: palette.offWhite,
    card: palette.white,
    border: palette.hairline,
    tint: palette.igBlue,
    tintSoft: palette.igBlueSoft,
    tabIconDefault: palette.mist,
    tabIconSelected: palette.nearBlack,
    accent: palette.accentGold,
    ayahNumber: palette.igBlue,
    arabic: palette.nearBlack,
    translation: '#555555',
    headerBg: palette.white,
    danger: palette.danger,
    overlay: 'rgba(0,0,0,0.4)',
    heroGradientStart: '#0B1A2A',
    heroGradientEnd: '#1A3A4A',
    primaryButton: palette.igBlue,
    primaryButtonText: palette.white,
  },
  dark: {
    text: '#F5F5F5',
    textSecondary: '#A8A8A8',
    background: palette.trueBlack,
    card: palette.surfaceDark,
    border: palette.hairlineDark,
    tint: palette.igBlue,
    tintSoft: palette.igBlueSoftDark,
    tabIconDefault: '#737373',
    tabIconSelected: '#F5F5F5',
    accent: palette.accentGold,
    ayahNumber: palette.igBlue,
    arabic: '#FAFAFA',
    translation: '#C7C7C7',
    headerBg: palette.trueBlack,
    danger: '#FF6B6B',
    overlay: 'rgba(0,0,0,0.55)',
    heroGradientStart: '#000000',
    heroGradientEnd: '#0D1F2D',
    primaryButton: palette.igBlue,
    primaryButtonText: palette.white,
  },
};

export { palette };
