const palette = {
  emerald: '#0D9488',
  emeraldDark: '#0F766E',
  emeraldLight: '#14B8A6',
  gold: '#C9A227',
  cream: '#F7F3EA',
  creamDark: '#EDE6D6',
  ink: '#1A1F2E',
  inkSoft: '#2A3142',
  mist: '#8B95A8',
  white: '#FFFFFF',
  black: '#0B0D12',
  danger: '#DC2626',
};

export default {
  light: {
    text: palette.ink,
    textSecondary: '#5A6478',
    background: palette.cream,
    card: palette.white,
    border: '#E5DFD0',
    tint: palette.emerald,
    tintSoft: '#CCFBF1',
    tabIconDefault: palette.mist,
    tabIconSelected: palette.emerald,
    accent: palette.gold,
    ayahNumber: palette.emerald,
    arabic: palette.ink,
    translation: '#4A5568',
    headerBg: palette.white,
    danger: palette.danger,
    overlay: 'rgba(26,31,46,0.4)',
  },
  dark: {
    text: '#F3F0E8',
    textSecondary: '#A0A8B8',
    background: palette.black,
    card: palette.inkSoft,
    border: '#3A4255',
    tint: palette.emeraldLight,
    tintSoft: '#134E4A',
    tabIconDefault: '#6B7280',
    tabIconSelected: palette.emeraldLight,
    accent: palette.gold,
    ayahNumber: palette.emeraldLight,
    arabic: '#F8F5EE',
    translation: '#C5CBD6',
    headerBg: palette.ink,
    danger: '#F87171',
    overlay: 'rgba(0,0,0,0.55)',
  },
};

export { palette };
